# Generated by Django 3.1.2 on 2020-12-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpAssigner', '0002_remove_vrplocation_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrplocation',
            name='countryCode',
            field=models.CharField(default='D', max_length=30),
        ),
        migrations.AlterField(
            model_name='vrplocation',
            name='city',
            field=models.CharField(default='Berlin', max_length=30),
        ),
        migrations.AlterField(
            model_name='vrplocation',
            name='cityCode',
            field=models.CharField(default='B', max_length=30),
        ),
        migrations.AlterField(
            model_name='vrplocation',
            name='country',
            field=models.CharField(default='Deutschland', max_length=30),
        ),
    ]
